#!/bin/bash
#
# Created by Voli

#:::::: Fix beallitasok :::::::
FORDULAT_MAX=3000
FORDULAT_HIBAS=23
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::
#:::::: functions :::::::::::::

if [ "$1" = "autoconf" ]; then
	echo yes 
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_category sensors'
	echo 'graph_title Ventillator fordulatszamok'
	echo 'graph_vtitle 1/perc [rpm]'
	echo 'graph_vlabel RPM'
	SorSzam=0
	sensors |grep "RPM"|sed 's/: .*//g'|while read a; do
		SorSzam=$[${SorSzam}+1];
		echo "Fan${SorSzam}.label ${a}"
		done
	exit 0
fi

#:::::: Start :::::::::::::::::
SorSzam=0
sensors |grep "RPM"|sed 's/RPM.*//g'|while read a; do
	SorSzam=$[${SorSzam}+1];
#	echo ${a}
	Ertek=`echo ${a}|sed 's/.* //g'`

	if [ ${Ertek} -gt ${FORDULAT_MAX} ]; then Ertek=${FORDULAT_HIBAS}
	fi

	echo "Fan${SorSzam}.value ${Ertek}"
done

exit 0