#!/bin/bash
#
#	Create by Voli

# Type of product: SHELLY DUO, SHELLY DUO GU10, SHELLY VINTAGE A60, SHELLY VINTAGE ST64, SHELLY VINTAGE G125, Shelly-Duo, Shelly-Vintage
#:::::: Fix beallitasok :::::::
def_ip=Shelly-Duo
#:::::: Beallitasok :::::::::::
#ignore='has_timer|temp'
    [ -z "$ignore" ] && ignore=URES
#:::::: functions :::::::::::::
ConfField(){
    eval "case \"$1\" in $ignore) return ;; esac"	## Ignore field
			echo "$1.label	$2"
    [ -n "$3" ] && 	echo "$1.info	$3"
}
Bool(){
    [ "$2" == "true"  ] && echo "$1.value 1"
    [ "$2" == "false" ] && echo "$1.value 0"
}

#:::::: Start :::::::::::::::::
if [ "$1" = "autoconf" ]; then  echo yes ; exit 0; fi

if [ "$1" = "config" ]; then
	[ -z "$vlabel" ] && vlabel=$( curl -s --connect-timeout 3  http://${address:-${def_ip}}/settings |sed 's|"||g; s|,|\n|g' |grep '^name:' | sed 's|.*:||' |grep -v null )
	echo	"graph_title ${title:-Shelly Duo light}"
	echo	"graph_vlabel ${vlabel:-Shelly Duo}"
	echo	"graph_category ${category:-Shelly}"
	ConfField	ison		"Channel is turned"	"Whether the channel is turned 1:ON / 0:OFF"
	ConfField	has_timer	"Timer is armed"	"Whether a timer is currently armed for this channel: 1"
	ConfField	brightness	"Brightness"		"Brightness, 0..100"
	ConfField	white		"White"			"White level, 0..100"
	ConfField	temp		"Color temperature"	"Color temperature, 2700..6500K (derived from white)"
	ConfField	power		"Power [W]"		"Consumed power [W]"
	ConfField	total		"Energy consumed [Wh]"	"Total energy consumed by the attached electrical appliance in Watt-hour"
	exit 0
fi

#:::::: Run :::::::::::::::::
	Result=$( curl -s --connect-timeout 3 http://${address:-${def_ip}}/status |sed 's|"||g; s|,|\n|g; s|\[{|\n|g; s|}\]||g' )
	[ -z "$Result" ] && exit 1
	echo "$Result" |while read a; do
	    IFS=':' read -r -a tmp <<< "$a";
	    eval "case \"${tmp[0]}\" in $ignore) continue ;; esac"	## Ignore field
		case ${tmp[0]} in
		    ison|has_timer)			Bool ${tmp[0]} ${tmp[1]}		;;
		    brightness|white|temp|power)	echo "${tmp[0]}.value ${tmp[1]}"	;;
		    total)				echo "${tmp[0]}.value $( bc <<< "scale=2; ${tmp[1]}/60")"	;;
		esac
	done
exit 0