#!/bin/bash
#
#	Create by Voli

# Type of product: SHELLY BULB, SHELLY DUO - RGBW, SHELLY DUO - RGBW GU10, Shelly-ColorBulb
#:::::: Fix beallitasok :::::::
def_ip=Shelly-ColorBulb
#:::::: Beallitasok :::::::::::
#ignore='total|temp'
    [ -z "$ignore" ] && ignore=URES
#:::::: functions :::::::::::::
ConfField(){
    eval "case \"$1\" in $ignore) return ;; esac"	## Ignore field
			echo "$1.label	$2"
    [ -n "$3" ] && 	echo "$1.info	$3"
}
Bool(){
    [ "$2" == "true"  ] && echo "$1.value 1"
    [ "$2" == "false" ] && echo "$1.value 0"
}

#:::::: Start :::::::::::::::::
if [ "$1" = "autoconf" ]; then  echo yes ; exit 0; fi

if [ "$1" = "config" ]; then
	[ -z "$vlabel" ] && vlabel=$( curl -s --connect-timeout 3  http://${address:-${def_ip}}/settings |sed 's|"||g; s|,|\n|g' |grep '^name:' | sed 's|.*:||' |grep -v null )
	echo	"graph_title ${title:-Shelly BULB color light}"
	echo	"graph_vlabel ${vlabel:-Shelly BULB}"
	echo	"graph_category ${category:-Shelly}"
	ConfField	ison		"Channel is turned"	"Whether the channel is turned 1:ON / 0:OFF"
	ConfField	has_timer	"Timer is armed"	"Whether a timer is currently armed for this channel: 1"
	ConfField	mode		"Configured mode"	"Currently configured mode: 0:white or 1:color"
	ConfField	red 		"Red brightness"	"Red brightness, 0..255, applies in mode=color"
	ConfField	green		"Green brightness"	"Green brightness, 0..255, applies in mode=color"
	ConfField	blue		"Blue brightness"	"Blue brightness, 0..255, applies in mode=color"
	ConfField	white		White			"White level, 0..100"
	ConfField	gain 		Gain			"Gain for all channels, 0..100, applies in mode=color"
	ConfField	brightness	Brightness		"Brightness, 0..100"
	ConfField	temp		"Color temperature"	"Color temperature in K, 3000..6500, applies in mode=white"
	ConfField	power		"Power [W]"		"Consumed power [W]"
	ConfField	total		"Energy consumed [Wh]"	"Total energy consumed by the attached electrical appliance in Watt-hour"
	exit 0
fi

#:::::: Run :::::::::::::::::
	Result=$( curl -s --connect-timeout 3 http://${address:-${def_ip}}/status |sed 's|"||g; s|,|\n|g; s|\[{|\n|g; s|}\]||g' )
	[ -z "$Result" ] && exit 1
	echo "$Result" |while read a; do
	    IFS=':' read -r -a tmp <<< "$a";
	    eval "case \"${tmp[0]}\" in $ignore) continue ;; esac"	## Ignore field
		case ${tmp[0]} in
		    mode)	case ${tmp[1]} in
					white) echo ${tmp[0]}.value 0	;;
					color) echo ${tmp[0]}.value 1	;;
				esac 	;;
		    ison|has_timer)	Bool ${tmp[0]} ${tmp[1]}						;;
		    total)		echo "${tmp[0]}.value $( bc <<< "scale=2; ${tmp[1]}/60")"		;;
		    brightness|red|green|blue|white|gain|temp|power)	echo "${tmp[0]}.value ${tmp[1]}"	;;
		esac
	done
exit 0