#!/bin/bash
#
# Plugin to monitor APC Power usage. by VolaricsI
#
#	loadpct és timeleft lehet a parameter
# Created by Voli

POWER_MAX=550		# A névleges W-os teljesítménye az UPS-nek: 500 helyet 550, hogy jó legyen a számolt teljesítmény.
POWER_MIN=16		# A minimális teljesítmény, ez korrekció: hozzáadásra kerül
POWER_CRIT=110		# Ennyi %-ot tud az UPS teljesitmenyre
			#Ennel nagyobb ertekek nem lehetnek
LOADPCT_LIMIT=550	#Ennyit tud az ÉN UPS-em
TIMELEFT_LIMIT=18	#18 percnél nagyobb áthidalási ido nincs

Mit=loadpct				#	Ha nincs "_valami" akkor ez lessz
MODEL="MODEL    : "			#	Innen veszi a Tipus meghatározását
PRG=/sbin/apcaccess			#	A használt program

#:::::: Start :::::::::::::::::
if [ "$1" = "autoconf" ]; then
	if [ -x ${PRG} ]; then	echo yes;	exit 0;	fi
	echo no;	exit 0
fi

#	Kikeresem a "_parameter"-t
P=$( basename $0|sed 's/.*_//g' )
if [ ".${P}" != "." ]; then
	Mit=${P}
fi

if [ "$1" = "config" ]; then
	echo "graph_title Tipus: $( ${PRG} status|grep "${MODEL}"|sed "s/${MODEL}//g" )"
	echo 'graph_args --base 1000'
	echo 'graph_category UPS'
	echo "graph_info This graph shows the UPS mit $Mit."
	case "${Mit}" in						#	A beállító rész. Az egyedieket itt kell beállítani:
		loadpct)	echo "graph_vlabel P [W]"
				echo "${Mit}.label Teljesitmeny [W]"
				echo "${Mit}.max ${POWER_MAX}"
				echo "${Mit}.warning ${POWER_MAX}"
				echo "${Mit}.critical $((${POWER_CRIT}*${POWER_MAX}/100))"
				echo "${Mit}.info A szunetmentes teljesitmenye."
		;;
		timeleft)	echo "graph_vlabel T [perc]"
				echo "${Mit}.label Futasi ido [perc]"
				echo "${Mit}.info A hatralevo ido."
		;;
		*)		echo "graph_vlabel ${Mit}"
			echo "${Mit}.label ${Mit}"
			echo "${Mit}.info A ${Mit} parameter."
		;;
	esac
	exit 0
fi


	Mit_Upper=$( echo ${Mit} |tr '[a-z]' '[A-Z]' )
	Ret=$( ${PRG}|grep "^${Mit_Upper}"|sed 's/.*: \+//g; s/ .*//g' )
	Ret_egesz=$( echo ${Ret}|sed 's/\.//g;' )

##	if [ ".${Ret}" = "." ]; 	then exit 0; fi;
	if [ ".${Ret_egesz}" = "." ]; 	then exit 0; fi;

	#	az egyedi dimenzionálást itt kell elvégezni.
	case "${Mit}" in
		loadpct)
			Ret=$((${Ret_egesz}*${POWER_MAX}/1000+${POWER_MIN}))
		;;
		timeleft)
			if [ ${Ret_egesz} -gt ${TIMELEFT_LIMIT}0 ]; then	## 10-es szorzó
				Ret=${TIMELEFT_LIMIT}
			fi
		;;
		*)
		;;
	esac

echo "${Mit}.value ${Ret}"
exit 0
