#!/bin/bash
#
#	Create by Voli

# Type of product: Shelly Plug S
#:::::: Fix beallitasok :::::::
    ConfFile=/etc/munin/plugin-conf.d/$( basename $0 )
    FieldLista=" power temperature overtemperature relay_ison overpower has_timer total "
#:::::: Beallitasok :::::::::::
    [ -e $ConfFile 	] && . $ConfFile
    [ -z "$Address" 	] && Address=localhost

    [ -z "$Category" 	] && Category='Shelly'
#Address=Shelly-Huto
    [ -n "$Ignore" 	] && ignore="$Ignore"
    [ -z "$ignore" 	] && ignore=URES			##Nem lehet üres

#:::::: functions :::::::::::::
ConfField(){
    eval "case \"$1\" in $ignore) return ;; esac"	## Ignore field
    [ -z "$2" ] && 	echo "$1.label	$1"
    [ -n "$2" ] && 	echo "$1.label	$2"
    [ -n "$3" ] && 	echo "$1.info	$3"
}
Bool(){
    [ "$2" == "true"  ] && echo "$1.value 1"
    [ "$2" == "false" ] && echo "$1.value 0"
}

#:::::: Start :::::::::::::::::
if [ "$1" = "autoconf" ]; then  echo yes ; exit 0; fi

if [ "$1" = "config" ]; then			## Alapértelmezetten kiolvasom
	[ -z "$Title" 	] && Title=$(  curl -s --connect-timeout 3 http://${Address}/shelly   |sed 's|.*type":"||; s|".*||' )
	[ -z "$Vlabel" 	] && Vlabel=$( curl -s --connect-timeout 3 http://${Address}/settings |sed 's|.*name":"||; s|".*||' )
	echo	"graph_category $Category"
	echo	"graph_title $Title"
	echo	"graph_vlabel $Vlabel"

	for f in $FieldLista  ; do
	    l="${f}_label" ;i="${f}_info"
	    ConfField "$f" "${!l}" "${!i}"
	done
	exit 0
fi

#:::::: Run :::::::::::::::::
	Result=$( curl -s --connect-timeout 3 http://${Address}/status |sed 's|"||g; s|,|\n|g; s|\[{|\n|g; s|}\]||g' )
	[ -z "$Result" ] && exit 1
	echo "$Result" |while read a; do
	    IFS=':' read -r -a tmp <<< "$a";
	    eval "case \"${tmp[0]}\" in $ignore) continue ;; esac"	## Ignore field
		case ${tmp[0]} in
		    overpower|overtemperature|has_timer)	Bool ${tmp[0]}        ${tmp[1]}		;;
		    ison)					Bool relay_${tmp[0]}  ${tmp[1]}		;;
		    total)					echo "${tmp[0]}.value $[${tmp[1]}/60]"	;;
		    temperature)				echo "${tmp[0]}.value ${tmp[1]}"	;;
		    power)					echo "${tmp[0]}.value ${tmp[1]}"	;;
		esac
	done
exit 0
