#!/bin/bash
#
#	Create by Voli

# Type of product: SHELLY H&T
#:::::: Fix beallitasok :::::::
    ConfFile=/etc/munin/plugin-conf.d/$( basename $0 )
#:::::: Beallitasok :::::::::::
    [ -e $ConfFile 	] && . $ConfFile
    [ -z "$SERVER" 	] && SERVER=localhost
    [ -z "$DEVICE" 	] && DEVICE='shellies'

    [ -z "$Category" 	] && Category='Shelly'
    [ -z "$Title" 	] && Title='Shellies eszközök álltal mért páratartalom'
    [ -z "$Vlabel" 	] && Vlabel='páratartalom [%]'

#:::::: functions :::::::::::::
ConfField(){
    [ -z "$2" ] && 	echo "$1.label	$1"			## Ha nincs megadva akkor is kell, hogy legyen
    [ -n "$2" ] && 	echo "$1.label	$2"
    [ -n "$3" ] && 	echo "$1.info	$3"
}

ValueList(){
    mosquitto_sub --quiet --host $SERVER -W 1 --topic "${DEVICE}/+/sensor/humidity" -v |sed "s|[-áéíóöőúüű]\+|_|g; s|^$DEVICE/||; s|/.* |.value |; "
}

#:::::: Start :::::::::::::::::
if [ "$1" = "autoconf" ]; then  echo yes ; exit 0; fi

if [ "$1" = "config" ]; then
    echo	"graph_title $Title"
    echo	"graph_vlabel $Vlabel"
    echo	"graph_category $Category"
			##Azok a betük melyek nem lehetnek változó nevek
    ValueList |sed 's|.value .*||; s|[-áéíóöőúüű]\+|_|g' |while read nev; do
        l="${nev}_label" ;i="${nev}_info"
        ConfField "$nev" "${!l}" "${!i}"
    done
    exit 0
fi

#:::::: Run :::::::::::::::::
    ValueList
exit 0
