#!/bin/bash
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
MAX_FORDULAT=3000
#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::
#:::::: functions :::::::::::::

if [ ".$1" = ".autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_category sensors'
	echo 'graph_title Ventillator fordulatszamok'
	echo 'graph_vtitle RPM'
#	echo 'graph_args --base 1000 -l 0'
#	echo 'graph_args --base 1000'
	echo 'graph_vlabel RPM'
	SorSzam=0
	sensors |grep "RPM"|sed 's/ .*//g'|while read a; do
		SorSzam=$[${SorSzam}+1];
		echo "Fan${SorSzam}.label ${a}"
#		echo "Fan${SorSzam}.min 0"
	    if [ $SorSzam = 4 ]; then break; fi
		done
	exit 0
fi

#:::::: Start :::::::::::::::::
SorSzam=0
sensors |grep "RPM"|sed 's/RPM.*//g'|while read a; do
	SorSzam=$[${SorSzam}+1];
#	echo ${a}
	Ertek=`echo ${a}|sed 's/.* //g'`

	if [ ${Ertek} -gt ${MAX_FORDULAT} ]; then Ertek=23; fi

	if [ ${Ertek} = 0 ]; then continue; fi

	echo "Fan${SorSzam}.value ${Ertek}"
done

exit 0