#!/usr/bin/perl -w
#
# xmlrpc based munin plugin for monitoring rTorrent's torrent count
# prerequisites:
#  - rTorrent 0.7.5 or newer compiled with --with-xmlrpc-c
# check http://libtorrent.rakshasa.no/wiki/RTorrentXMLRPCGuide for further informations
#
# written by Gabor Hudiczius
# web: http://rtwi.jmk.hu/wiki/rTorrentOMeter
# email: ghudiczius@gmail.com
#
#
# Parameters:
#
#	config		required
#
#
# Configurable variables
#
#	src			"socket" when using scgi_socket, or anything else when using scgi_port
#	socket		rTorrent's rpc socket (scgi_local)	- using scgi_local	- needed, when "src" is set to "socket"
#	ip			rTorrent's ip address				- using scgi_port	- needed, when "src" is NOT set to "socket"
#	port		rTorrent's scgi port (scgi_port)	- using scgi_port	- needed, when "src" is NOT set to "socket"
#
#	diff		not used
#
#
# Configuration example
#
#	[rtom__vol]
#	user username
#	env.src socket
#	env.socket /home/username/torrent/.socket/rpc.socket
#
#	[rtom__vol]
#	env.ip 127.0.0.1
#	env.port 5000
#
#
#%# family=auto

my $src 		= $ENV{"src"} || "";
my $ip			= $ENV{"ip"} || "127.0.0.1";
my $port		= $ENV{"port"} || 5000;
my $socket		= $ENV{"socket"} || "";
my $diff		= $ENV{"diff"} || 0;

#if ( $0 =~ /^(?:|.*\/)rtom_(.*)_vol$/ ) {
#    $user = " for ${1}";
#} else {
    $user = "";
#}

if ( $ARGV[0] and $ARGV[0] eq "autoconf" ) {
	exit 1;
}

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
	print "graph_title rTorrent volume${user}\n";
	print "graph_args --base 1000 -r --lower-limit 0\n";
	print "graph_vlabel Torrents\n";
	print "graph_category rTorrent${user}\n";
	print "complete.label complete\n";
	print "complete.info number of complete torrents\n";
	print "complete.type GAUGE\n";
	print "complete.min 0\n";
	print "complete.draw AREA\n";
	print "incomplete.label incomplete\n";
	print "incomplete.info number of incomplete torrents\n";
	print "incomplete.type GAUGE\n";
	print "incomplete.min 0\n";
	print "incomplete.draw STACK\n";
	print "stopped.label stopped\n";
	print "stopped.info number of stopped torrents\n";
	print "stopped.type GAUGE\n";
	print "stopped.min 0\n";
	print "stopped.draw LINE2\n";
	print "started.label started\n";
	print "started.info number of started torrents\n";
	print "started.type GAUGE\n";
	print "started.min 0\n";
	print "started.draw LINE2\n";
	print "active.label active\n";
	print "active.info number of active torrents\n";
	print "active.type GAUGE\n";
	print "active.min 0\n";
	print "active.draw LINE2\n";
	print "hashing.label hashing\n";
	print "hashing.info number of hashing torrents\n";
	print "hashing.type GAUGE\n";
	print "hashing.min 0\n";
	print "hashing.draw LINE2\n";
	print "total.label total\n";
	print "total.info total number of torrents\n";
	print "total.type GAUGE\n";
	print "total.min 0\n";
	print "total.draw LINE2\n";
	exit 0;
}

use IO::Socket;

my $pattern	= qr/<value><(int|i4|i8|ex\.i8)>(\d+)<\/(int|i4|i8|ex\.i8)><\/value>/;

my $line	= "<?xml version=\"1.0\" encoding=\"utf-8\"?><methodCall><methodName>d.multicall</methodName><params><param><value><string>default</string></value></param><param><value><string>d.get_hash=</string></value></param><param><value><string>d.get_state=</string></value></param><param><value><string>d.get_complete=</string></value></param><param><value><string>d.is_active=</string></value></param><param><value><string>d.is_hash_checking=</string></value></param></params></methodCall>";
my $llen	= length $line;
my $header	= "CONTENT_LENGTH\000${llen}\000SCGI\001\000";
my $hlen	= length $header;
$line	= "${hlen}:${header},${line}";

if ( $src eq "socket" ) {
	socket( SOCK, PF_UNIX, SOCK_STREAM, 0 );
	connect( SOCK, sockaddr_un( $socket ) );
} else {
	socket( SOCK, PF_INET, SOCK_STREAM, getprotobyname( "tcp" ) );
	connect( SOCK, sockaddr_in( $port, inet_aton( $ip ) ) );
}

print SOCK $line;
flush SOCK;

my $tot = 0;
my $sta = 0;
my $sto = 0;
my $com = 0;
my $inc = 0;
my $act = 0;
my $has = 0;

while ( $line = <SOCK> ) {
	if ( $line =~ /$pattern/ ) {
		$tot++;
		if ( $2 == 1 ) {
			$sta++;
		} else {
			$sto++;
		}

		$line = <SOCK>;
		$line =~ /$pattern/;
		if ( $2 == 1 ) {
			$com++;
		} else {
			$inc++;
		}

		$line = <SOCK>;
		$line =~ /$pattern/;
		if ( $2 == 1 ) {
			$act++;
		}

		$line = <SOCK>;
		$line =~ /$pattern/;
		if ( $2 == 1 ) {
			$has++;
		}
	}
}

close (SOCK);

print "total.value ${tot}\nstarted.value ${sta}\nstopped.value ${sto}\ncomplete.value ${com}\nincomplete.value ${inc}\nactive.value ${act}\nhashing.value ${has}\n";
exit;
