#!/usr/bin/perl -w
#
# xmlrpc based munin plugin for monitoring rTorrent's peer count
# prerequisites:
#  - rTorrent 0.7.5 or newer compiled with --with-xmlrpc-c
# check http://libtorrent.rakshasa.no/wiki/RTorrentXMLRPCGuide for further informations
#
# written by Gabor Hudiczius
# web: http://rtwi.jmk.hu/wiki/rTorrentOMeter
# email: ghudiczius@gmail.com
#
#
# Parameters:
#
#	config		required
#
#
# Configurable variables
#
#	src			"socket" when using scgi_socket, or anything else when using scgi_port
#	socket		rTorrent's rpc socket (scgi_local)	- using scgi_local	- needed, when "src" is set to "socket"
#	ip			rTorrent's ip address				- using scgi_port	- needed, when "src" is NOT set to "socket"
#	port		rTorrent's scgi port (scgi_port)	- using scgi_port	- needed, when "src" is NOT set to "socket"
#
#	diff		not used
#
#
# Configuration example
#
#	[rtom__peers]
#	user username
#	env.src socket
#	env.socket /home/username/torrent/.socket/rpc.socket
#
#	[rtom__peers]
#	env.ip 127.0.0.1
#	env.port 5000
#
#
#%# family=auto

my $src 		= $ENV{"src"} || "";
my $ip			= $ENV{"ip"} || "127.0.0.1";
my $port		= $ENV{"port"} || 5000;
my $socket		= $ENV{"socket"} || "";
my $diff		= $ENV{"diff"} || 0;

#if ( $0 =~ /^(?:|.*\/)rtom_(.*)_peers$/ ) {
#    $user = " for ${1}";
#} else {
    $user = "";
#}

if ( $ARGV[0] and $ARGV[0] eq "autoconf" ) {
	exit 1;
}

if ( $ARGV[0] and $ARGV[0] eq "config" ) {
	print "graph_title rTorrent peer statistics${user}\n";
	print "graph_args --base 1000 --lower-limit 0\n";
	print "graph_vlabel Peers\n";
	print "graph_category rTorrent${user}\n";
	print "outgoing.label outgoing\n";
	print "outgoing.info number of outgoing connections\n";
	print "outgoing.type GAUGE\n";
	print "outgoing.min 0\n";
	print "outgoing.draw AREA\n";
	print "incoming.label incoming\n";
	print "incoming.info number of incoming connections\n";
	print "incoming.type GAUGE\n";
	print "incoming.min 0\n";
	print "incoming.draw STACK\n";
	print "plain.label plain text\n";
	print "plain.info number of plain text connections\n";
	print "plain.type GAUGE\n";
	print "plain.min 0\n";
	print "plain.draw LINE2\n";
	print "encrypted.label encrypted\n";
	print "encrypted.info number of encrypted connections\n";
	print "encrypted.type GAUGE\n";
	print "encrypted.min 0\n";
	print "encrypted.draw LINE2\n";
	print "total.label total\n";
	print "total.info total number of connections\n";
	print "total.type GAUGE\n";
	print "total.min 0\n";
	print "total.draw LINE2\n";
 	exit 0;
}

use IO::Socket;

my $pattern	= qr/<value><(int|i4|i8|ex\.i8)>(\d+)<\/(int|i4|i8|ex\.i8)><\/value>/;

my $line	= "<?xml version=\"1.0\" encoding=\"utf-8\"?><methodCall><methodName>d.multicall</methodName><params><param><value><string>default</string></value></param><param><value><string>d.get_hash=</string></value></param><param><value><string>p.multicall=,p.is_encrypted=,p.is_incoming=</string></value></param></params></methodCall>";
my $llen	= length $line;
my $header	= "CONTENT_LENGTH\000${llen}\000SCGI\001\000";
my $hlen	= length $header;
$line		= "${hlen}:${header},${line}";

if ( $src eq "socket" ) {
	socket( SOCK, PF_UNIX, SOCK_STREAM, 0 );
	connect( SOCK, sockaddr_un( $socket ) );
} else {
	socket( SOCK, PF_INET, SOCK_STREAM, getprotobyname( "tcp" ) );
	connect( SOCK, sockaddr_in( $port, inet_aton( $ip ) ) );
}

print SOCK $line;
flush SOCK;

my $tot = 0;
my $enc = 0;
my $inc = 0;

while ( $line = <SOCK> ) {
	if ( $line =~ /$pattern/ ) {
		$tot++;
		$enc += $2;
		$line = <SOCK>;
		$line =~ /$pattern/;
		$inc += $2;
	}
}

close (SOCK);

my $out = $tot - $inc;
my $pla = $tot - $enc;

print "total.value ${tot}\nencrypted.value ${enc}\nplain.value ${pla}\nincoming.value ${inc}\noutgoing.value ${out}\n";

exit;
