#!/bin/bash
#
# Plugin to monitor Idokep automata.by VolaricsI
#
# Parameters understood:
#
# 	config   (required)
# 	autoconf (optional - used by munin-config)
#

#HOST="192.168.0.90"
HOST="idokep_automata"

URL="http://${HOST}/cgi-bin/luci/admin/status/automata/"

ADATLAP=/tmp/Idokep_	#Ide kerül a szürt kiolvasás
Mit="homerseklet"	#Meg ezeket tudja: homerseklet; paratartalom; legnyomas; Csapadek; _szel;

function GetMit(){
	wget -t 1 -T 5 -nv -o /dev/null -O -  "${URL}" \
	|sgrep '"<h2>WS23XX m&eacute;rt adatai</h2> " .. "<h2>TE923/TE823 m&eacute;rt adatai</h2>"' 	|grep -v -e "^<.*> *$" -e "^$"|sed 's/<pre>//g; ' \
	|grep "${Mit}" 	>${ADATLAP}
}


#:::::: Start :::::::::::::::::
if [ "$1" = "autoconf" ]; then
	echo yes;	exit 0
fi

H=$( basename $0|sed 's/.*_//g' )
if [ ".${H}" != "." ]; then
	Mit=${H}
fi

ADATLAP=${ADATLAP}${Mit}

    [ ".$1" == "."  -o   ! -e ${ADATLAP} ] && GetMit

if [ ".$1" = ".config" ]; then
	echo	'graph_category Idokep'
	echo	'graph_args --base 1000'
	echo	"graph_title Idokep ${Mit}"
	echo	"graph_vlabel Idokep ${Mit}"
	echo	"graph_info This graph shows the ${Mit}"
	case "${Mit}" in
		legnyomas)
			echo "graph_args --upper-limit 1100 --lower-limit 900"
		;;
		paratartalom)
			echo "graph_args --upper-limit 100 --lower-limit 0 --rigid"
		;;
		*)
		#
		;;
	esac
	cat ${ADATLAP}	|sed 's/=.*//g'		\
	|while read a; do
		echo "${a}.label ${a}"
	done
	rm  ${ADATLAP}; exit 0
fi

	cat ${ADATLAP}	|sed 's/=/.value /g; '
	rm ${ADATLAP}; 	exit 0
