#!/bin/bash
#
#	Create by Voli

#:::::: Fix beallitasok :::::::
MODEM_SRC=http://192.168.100.1/Docsis_system.asp

ADATLAP=/var/lib/munin-node/plugin-state/ModemLikSys.html

ADATLAP=/tmp/ModemLikSys.html

TMP_FILE=/tmp/$( basename $0 )$$

DOWN_POWER_CH="Le_Jelszint_ch"
DOWN_JELZAJ_CH="Le_Zajszint_ch"
UP_POWER_CH="Fel_Jelszint_ch"

#:::::: Beallitasok :::::::::::
#:::::: Ellenorzesek ::::::::::
#:::::: functions :::::::::::::
function Letoltes(){
	wget -t 1 -T 10 -O - ${MODEM_SRC}	2>/dev/null		\
	|sgrep '"<body " .. "</body>"'					\
	|sgrep '"<!-- Downstream Channel Information Start -->" .. "<!-- Upstream Channel Information End -->"'					\
	|sgrep -a -o "" '"<script" .. "</script>"'			\
	>"${TMP_FILE}"
	date +"%Y.%m.%d %H:%M:%S $0 $*"		>>"${TMP_FILE}"
	mv --force "${TMP_FILE}" ${ADATLAP}
	[ -e "${TMP_FILE}" ] && rm "${TMP_FILE}"
}
function Get_Upstream(){
	cat ${ADATLAP}	\
	|sgrep '"<!-- Upstream Channel Information Start -->" .. "<!-- Upstream Channel Information End -->"'		\
	|grep "<td class=\"stdbold\" nowrap>"	|sed 's/<\/td>$//g; s/.*>//g; s/ //g; '
}
function Get_Downstream(){
	cat ${ADATLAP}	\
	|sgrep '"<!-- Downstream Channel Information Start -->" .. "<!-- Downstream Channel Information End -->"'	\
	|sgrep '"<table class=\"std\">" .. "</table>"'		\
	|grep "<td class=\"stdbold\" nowrap>[ 0-9.]\+</td>"	\
	|sed 's/<\/td>$//g; s/^.\+>//g;'	\
	|while read a; read b; do
		echo "${a}/${b}"
	done
}
function PrintValue(){
	SorSzam=0
	while read a; do
		SorSzam=$[${SorSzam}+1];	echo $1${SorSzam}.value ${a}
	done
}
function Set_Conf(){
	sr=0;
	while read a; do
		sr=$[${sr}+1];	echo "$1${sr}.label $2${sr}"
	done
}


#:::::: Start :::::::::::::::::
if [ "$1" = "autoconf" ]; then
	echo yes 
exit 0
fi

    [ ".$1" == "."  -o   ! -e ${ADATLAP} ] && Letoltes


if [ "$1" = "config" ]; then
	echo 'graph_category modem'
	echo 'graph_args --base 1000'
	echo "graph_title  Cisco EPC3212 adatai"
	echo "graph_vlabel Voli-proba"
	echo "graph_info This graph shows the LinkSys Modem."

	Get_Downstream	|Set_Conf "${DOWN_POWER_CH}"	"Le  jel: "
	Get_Downstream	|Set_Conf "${DOWN_JELZAJ_CH}"	"Le  zaj: "
	Get_Upstream	|Set_Conf "${UP_POWER_CH}"	"Fel jel: "
	rm ${ADATLAP}
	exit 0
fi

	Get_Downstream		|sed 's/\/.*$//g;'	|PrintValue	"${DOWN_POWER_CH}"
	Get_Downstream		|sed 's/^.*\///g;'	|PrintValue	"${DOWN_JELZAJ_CH}"
	Get_Upstream					|PrintValue	"${UP_POWER_CH}"
	rm ${ADATLAP}
	exit 0
